### ISSUE TITLE
Create a wireframe of the application

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v23-toucans-team-02#10]
**Feature Description**
Create a wireframe of the application to define the layout of each screen & dialog along with the default styles to be used (e.g. fonts, colors, text sizes, etc.). This will also identify the parts of the screen users can interact with and the expected behavior of clicks, data entry, etc.

**Major User Stories**
- [x] As a Developer I need to understand app theme (e.g. fonts, colors, text sizes, etc.)  so I can develop to a standard along with other teammates
- [x] As a Developer I need to understand the layout of each screen so I can develop to a standard along with other teammates
- [x] As a Developer I need to understand what parts of the screen users can interact with and the expected results so I can implement the desired functionality

**Additional Considerations**
N/a

**Comment by tomrhudson** [comment]
The wireframes that @OmarAlareeki developed are great and I believe that this issue can be closed.

**Comment by jdmedlock** [comment]
## Smartphone
![image](https://user-images.githubusercontent.com/1287072/92420875-5fbfef00-f13b-11ea-87d4-6dfe789c138e.png)

## Tablet
![image](https://user-images.githubusercontent.com/1287072/92420883-6ea6a180-f13b-11ea-8ff7-7a29d76bcb45.png)

## Laptop
![image](https://user-images.githubusercontent.com/1287072/92420903-8716bc00-f13b-11ea-8532-767e8e224008.png)

**Comment by tomrhudson** [comment]
@jdmedlock can this be moved to QA/Review or closed?

**Comment by OmarAlareeki** [comment]
Should be closed.
