### ISSUE TITLE
Setup Project Repo

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v23-toucans-team-02#2]
**Task Description**
Setup the project repo based on the technical stack chosen by the team.

- [ ] Create folder structure
- [ ] Setup `package.json` with known dependencies
- [ ] Create fixed branches based on the Git Workflow decided on by the team
- [x] Create an initial `readme.md`. See [Keys to a Well Written Readme](https://tinyurl.com/y4lgfwj5) for examples

**Technical Considerations**
Include any technical considerations including architecture (e.g. API), required libraries, etc.

**Additional Considerations**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.
