### ISSUE TITLE
Support a responsive UI

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v23-toucans-team-02#3]
**Feature Description**
The Weather App should be responsive across a variety of device types & screen sizes including phones, tablets, laptops, & large screen devices. This should be implemented throughout the app and it's strongly suggested that developers follow a "mobile-first" strategy.

**Major User Stories**
- [ ] As an end user I want to use the app on my phone
- [ ] As an end user I want to use the app on my tablet
- [ ] As an end user I want to use the app on my laptop
- [ ] As an end user I want to use the app on my desktop

**Additional Considerations**
[Responsive Web Design Basics](https://web.dev/responsive-web-design-basics/)
[Responsive Web Design Fundamentals (free Udacity course)](https://tinyurl.com/y5yd2elo)

**Comment by jdmedlock** [comment]
This Epic was created as an requirement for all UI/UX related epics & user stories. It's purpose is to act as a reminder that we should follow a "mobile first" strategy.
