### ISSUE TITLE
Migrate from City/Zip to Latitude & Longitude 

### ISSUE THREAD

**Issue by tomrhudson** [chingu-voyages/v23-toucans-team-02#39]
**Task Description**
Change the user input from the city (due to duplicate cities) and zip code (as not all places have zip code) to using latitude and longitude.

**Technical Considerations**

- [x] This will require a change in the OpenWeatherMap API in weather.js
- [x] changes to index.html for user inpu
- [x] data validation on user input to ensure that the entered lat and long are within the range
