### ISSUE TITLE
Create a Landing Page

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v23-toucans-team-02#4]
**Feature Description**
The Landing page is the first page displayed with the app is started. It will contain:
- User location:  country, state, city
- Time in the users locale:   day, time
- Temperature at the users location:  { fahrenheit , celsius }
- Icon:  weather's type icon: cloudy, rainy, windy, shiny, snow, etc.
- Background image for the current weather type at the users location: cloudy, rainy, windy, shiny, snow, etc.
- The user should be able to select the unit of measure, fahrenheit or celcius, the temperature is to be displayed in.

**Major User Stories**
- [ ] As an end user I want to see my location (country, state, city) displayed on the screen so I can verify my location
- [ ] As an end user I want to see the current date & time displayed on the screen so I can easily reference it
- [ ] As an end user I want to see the current temperature in my preferred unit of measure (fahrenheit or celcius) displayed on the screen so I can easily reference it
- [ ] As an end user I want to see the current weather conditions summarized as an icon on the screen so I can easily reference it
- [ ] As an end user I want to see the background image of the page change based on the current weather conditions so I can use it as a quick reference to current conditions
- [ ] As an end user I want do select the unit of measure for temperatures so it reflects my regional standard

**Additional Considerations**
[Tabler Icons (SVG)](https://tablericons.com/)
[Geolocation API (MDN)](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API)
[OpenWeather API](https://openweathermap.org/api)
[Celcius to Fahrenheit formula](https://www.rapidtables.com/convert/temperature/how-celsius-to-fahrenheit.html)
[Fahrenheit to Celcius formula](https://www.rapidtables.com/convert/temperature/fahrenheit-to-celsius.html)

*_Questions_*
1. What other customizations might we want to support? For example, explicit setting of user location to override geolocation?

**Comment by thiagorasouza** [comment]
On Question 1.
As an end user, I usually only look for the weather of the place I'm going to, since I know what to expect at my city. So yep, I think it would be a good idea to let the user override the device's location.
